FROM ghcr.io/sigstore/cosign/cosign:v3.0.2 as cosign-bin
FROM ghcr.io/oras-project/oras:v1.3.0 as oras-bin

FROM quay.io/fedora/fedora:43

RUN <<EORUN
set -euxo pipefail
sed -i "s/enabled=1/enabled=0/" "/etc/yum.repos.d/fedora-cisco-openh264.repo"
dnf -y update

dnf -y install \
    bind-utils \
    borgbackup \
    fd-find \
    flatpak-spawn \
    fzf \
    gh \
    git-delta \
    inotify-tools \
    jq \
    just \
    make \
    mkpasswd \
    pinentry-tty \
    ripgrep \
    skopeo \
    nvim \
    tmux \
    yq

# Dev stuff
dnf -y install \
    ShellCheck \
    black \
    clang-format \
    g++ \
    gcc \
    golang \
    gdisk \
    krb5-devel \
    kustomize \
    openssl-devel \
    pylint \
    python3-pip \
    yamllint

# Packaging stuff
dnf -y install \
    createrepo_c \
    fedpkg \
    mock \
    rpmdevtools

dnf -y install \
    ImageMagick \
    convert \
    poppler-utils \
    slurp \
    zathura \
    zathura-pdf-poppler

# Openshift tools not shipped in Fedora repo, nor a container image
URLS="""
https://mirror.openshift.com/pub/openshift-v4/clients/pipelines/latest/tkn-linux-amd64.tar.gz
https://mirror.openshift.com/pub/openshift-v4/clients/oc/latest/linux/oc.tar.gz
"""
tarball="/tmp/tarball.tar.gz"
tmp_dir="/tmp/bin"
mkdir -p $tmp_dir
for url in $URLS; do
    curl -L $url -o $tarball && tar -xvf $tarball --no-same-owner -C $tmp_dir && rm -f $tarball
done
mv ${tmp_dir}/{oc,kubectl,opc,tkn,tkn-pac} /usr/local/bin && rm -rf $tmp_dir

# Remove unused setuid root program
dnf -y remove mlocate

dnf clean all
ln -snf /run/host/run/libvirt /run/libvirt
EORUN

# Tools that are not shipped in Fedora or not up-to-date
# This list needs to be revisited frequently as we want to privilege software rebuilt
# in Fedora build system for more guaranty.
COPY --from=cosign-bin /ko-app/cosign /usr/local/bin/cosign
COPY --from=oras-bin /bin/oras /usr/local/bin/oras

# Setup host-runner script and symlinks
# From https://github.com/travier/quay-containerfiles/blob/main/toolbox/Containerfile
COPY host-runner /usr/local/bin/host-runner
RUN <<EORUN
set -euxo pipefail
bins=(
    "flatpak"
    "podman"
    "rpm-ostree"
    "systemctl"
);
for f in "${bins[@]}"; do
    ln -s host-runner /usr/local/bin/$f;
done
EORUN
