FROM ghcr.io/sigstore/cosign/cosign:v3.0.2 as cosign-bin
FROM ghcr.io/oras-project/oras:v1.3.0 as oras-bin

FROM quay.io/fedora/fedora:43

# Install all packages via shared script
COPY install-packages.sh /tmp/
RUN chmod +x /tmp/install-packages.sh && /tmp/install-packages.sh && rm /tmp/install-packages.sh

# Create libvirt symlink for host access
RUN ln -snf /run/host/run/libvirt /run/libvirt

# Tools that are not shipped in Fedora or not up-to-date
# This list needs to be revisited frequently as we want to privilege software rebuilt
# in Fedora build system for more guaranty.
COPY --from=cosign-bin /ko-app/cosign /usr/local/bin/cosign
COPY --from=oras-bin /bin/oras /usr/local/bin/oras

# Setup host-runner script and symlinks
# From https://github.com/travier/quay-containerfiles/blob/main/toolbox/Containerfile
COPY host-runner /usr/local/bin/host-runner
RUN <<EORUN
set -euxo pipefail
bins=(
    "flatpak"
    "podman"
    "rpm-ostree"
    "systemctl"
);
for f in "${bins[@]}"; do
    ln -s host-runner /usr/local/bin/$f;
done
EORUN
